### ISSUE TITLE
Installation Improvements

### ISSUE THREAD

**Issue by xinli-centml** [CentML/habitat#19]
I tried to install habitat on an HPC environment where sudo access was not available, I managed to get it to work but had to manually change a few things.

1. CUPTI installation: instead of using `sudo apt` , I had to use `conda install -c "nvidia/label/cuda-11.6.0" cuda-cupti` from [conda](https://anaconda.org/nvidia/cuda-cupti). In general, I find this more convineint as it does not require root access and allows more flexible package management (user could already have cupti installed in system dir with different version)
2. After installing CUPTI, I had to modify LD_LIBRARY_PATH to `CONDA_HOME/extras/CUPTI/lib64/`
3. The wheel link on Github's README does not work, the link with s3 bucket works but is not publicly available.

I was thinking if we could provide a root-less installation option with conda? also to publish the correct link to the wheel file.

**Comment by michaelshin** [comment]
I'll add the conda instructions into the README and I will fix the URL

**Comment by xinli-centml** [comment]
yes, also with regards to the profiling permission issue, is there a way to check this ?
i.e. under pre-requisite, we first ensure users have permission to perform profiling on the GPU?

I have not hit the permission issue personally but was wondering if that would come up more often in other environments.

**Comment by michaelshin** [comment]
Not sure why but I don't see Xin's comment but I got an email about it. Here it is quoted:
> yes, also with regards to the profiling permission issue, is there a way to check this ?
i.e. under pre-requisite, we first ensure users have permission to perform profiling on the GPU?
> I have not hit the permission issue personally but was wondering if that would come up more often in other environments.

I can attach more documentation about this issue. Essentially a user can follow the [instructions](https://developer.nvidia.com/nvidia-development-tools-solutions-err_nvgpuctrperm-permission-issue-performance-counters) given by NVIDIA. However, a user needs sudo to make these changes which might be an issue

**Comment by xinli-centml** [comment]
I deleted the message because I feel like this might not be a priority issue. 
I didn't need the permission mentioned above to run Habitat, perhaps this was not needed in the prediction phase?

**Comment by michaelshin** [comment]
I noticed it was needed when I ran on GCP instances. It's better to highlight it to make it easier for users to fix their issues,
